<a href="https://colab.research.google.com/github/lorenzo1285/Algebra_lineal/blob/main/Act_5_gausjordan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from numpy import array, zeros, fabs, linalg

In [ ]:
# Funcion de Metodo Gauss Jordan
def gauss_jordan(a,b):

  a = np.array(a, float)
  b = np.array(b, float)
  n = len(b)
  x = zeros(n, float)

 #El primer bucle especifica la fila fija
  for k in range(n-1):
    if fabs(a[k,k]) < 1.0e-12:
        
        for i in range(k+1, n):
            if fabs(a[i,k]) > fabs(a[k,k]):
                a[[k,i]] = a[[i,k]]
                b[[k,i]] = b[[i,k]]
                break

 #aplica la eliminación por debajo de la fila fija

    for i in range(k+1,n):
        if a[i,k] == 0:continue

        factor = a[k,k]/a[i,k]
        for j in range(k,n):
            a[i,j] = a[k,j] - a[i,j]*factor
        
        #Calculo del vector b en cada columna
        b[i] = b[k] - b[i]*factor



  x[n-1] = b[n-1] / a[n-1, n-1]
  for i in range(n-2, -1, -1):
    sum_ax = 0
  
    for j in range(i+1, n):
        sum_ax += a[i,j] * x[j]
        
    x[i] = (b[i] - sum_ax) / a[i,i]

  inv = linalg.inv(a)
  array1 = np.matmul(a, inv)  
  
  print("La solución del sistema es:")
  print(x)
  print('Matriz Identidad:')
  print(array1)

Metodo de Gauss

1.)

2𝑥 + 𝑦 − 𝑧 = 8

−3𝑥 − 𝑦 + 2𝑧 = −11

−2𝑥 + 𝑦 + 2𝑧 = −3


In [ ]:
g_a = np.array([[2,1,-1],
                [-3,-1,2],
                [-2,1,2]])
g_b = np.array([[8],
                [-11],
                [-3]])

In [ ]:
gauss_jordan(g_a, g_b)

La solución del sistema es:
[ 2.  3. -1.]
Matriz Identidad:
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00 -1.48029737e-16]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]



2.)

6𝑥1 − 2𝑥2 − 2𝑥3 = 8 

2𝑥1 + 2𝑥2 + 𝑥3 = 3 

𝑥1 + 2𝑥2 + 2𝑥3 = −1

In [ ]:
g_a1 = np.array([[6,-2,-2],
                 [2,2,1],
                 [1,2,2]])

g_b1 = np.array([[8],
                 [3],
                 [-1]])

In [ ]:
gauss_jordan(g_a1, g_b1)

La solución del sistema es:
[ 1.  2. -3.]
Matriz Identidad:
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00 -5.55111512e-17]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


Metodo Gauss Jordan

3.)

3𝑥 + 2𝑦 + 𝑧 = 1

5𝑥 + 3𝑦 + 4𝑧 = 2

𝑥 + 𝑦 − 𝑧 = 1


In [ ]:
j_a = np.array([[3,2,1],
                [5,3,4],
                [1,1,-1]])

j_b = np. array([[1],
                 [2],
                 [1]])

In [ ]:
gauss_jordan(j_a, j_b)

La solución del sistema es:
[-4.  6.  1.]
Matriz Identidad:
[[ 1.00000000e+00  0.00000000e+00 -1.11022302e-15]
 [ 0.00000000e+00  1.00000000e+00 -1.92438658e-16]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


4.)

2𝑥 − 𝑦 + 3𝑧 = −3

𝑥 + 𝑦 + 𝑧 = 2

3𝑥 + 2𝑦 − 𝑧 = 8


In [ ]:
j_a1 = np.array([[2,-1,3],
                 [1,1,1],
                 [3,2,-1]])

j_b1 = np.array([[-3],
                 [2],
                 [8]])

In [ ]:
gauss_jordan(j_a1, j_b1)

La solución del sistema es:
[ 1.  2. -1.]
Matriz Identidad:
[[ 1.00000000e+00  0.00000000e+00  5.55111512e-17]
 [ 0.00000000e+00  1.00000000e+00 -5.55111512e-17]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
