<a href="https://colab.research.google.com/github/lorenzo1285/Algebra_lineal/blob/main/Alg_lon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

En los ejercicios a) al g), 

𝑢⃗ = (−1,3,4, −2), 

𝑣 = (−2,5,3,2) 

y 𝑤⃗ = (1,0,4, −2)


In [ ]:
u = np.array([-1,3,4,-2])
v = np.array([-2,5,3,2])
w = np.array([1,0,4,-2])

In [ ]:
# a) Calcular 3𝑢⃗ -4𝑣 
3*u -4*v


array([  5, -11,   0, -14])

In [ ]:
# b) Encontrar 𝑢⃗ + 1/2 w

u + (.5*w)

array([-0.5,  3. ,  6. , -3. ])

In [ ]:
# c) Hallar ‖𝑣 ‖
np.linalg.norm(v)

6.48074069840786

In [ ]:
# d) Calcular 𝑑(𝑢⃗ , 𝑤⃗ )
np.linalg.norm(u-w)

3.605551275463989

In [ ]:
# e) Hallar 4𝑢⃗ − 2𝑣 − w
4*u -2*v -w

array([ -1,   2,   6, -10])

In [ ]:
# f) Calcular 𝑢⃗ ∙ (𝑣 + 𝑤⃗ )
u * (v+w)

array([ 1, 15, 28,  0])

In [ ]:
# g) Encontrar el valor de b tal que (−1, 𝑏, 1, −2) ⊥ 𝑢⃗ , es decir, para que estos
#    vectores sean ortogonales.

# (−1, 𝑏, 1, −2) * (−2,5,3,2)
# 2 +5b +3 -4 = 0
# 5b + 1 = 0
# 5b = -1
# b = -1/5


2. Calcula el volumen de la “caja” construida sobre los tres vectores siguientes:
𝑎⃗⃗1 = (1,1,2), 𝑎⃗⃗⃗⃗2 = (3, 1,0), 𝑎⃗⃗⃗⃗3 = (−2, 0,3)


In [ ]:
a = np.array([[1,1,2],
             [3,1,0],
             [-2,0,3]])

np.linalg.det(a).round(5)

-2.0

In [ ]:
a_1 = np.array([[1,3,-2],
                [1,1,0],
                [2,0,3]])
np.linalg.det(a_1)

-2.0000000000000004

3. Determina si 𝑏⃗ es combinación lineal de 𝑎⃗⃗1 , 𝑎⃗⃗⃗⃗2 𝑦 𝑎⃗⃗⃗⃗3 .

𝑏⃗ = (2, −1,6); 𝑎⃗⃗1 = (1, −2,0), 𝑎⃗⃗⃗⃗2 = (0, 1, 2), 𝑎⃗⃗⃗⃗3 = (5, −6, 8)

𝑏⃗ = (11, −5,9); 𝑎⃗⃗1 = (1,0,1), 𝑎⃗⃗⃗⃗2 = (−2, 3, −2), 𝑎⃗⃗⃗⃗3 = (−6, 7, 5)


In [ ]:
b_1 = np.array([[2],
               [-1],
               [ 6]])

a_1 = np.array([[1,0, 5],
               [-2,1,-6],
               [ 0,2, 8]])

b_2 = np.array([[11],
                [-5],
                [9]])

a_2 = np.array([[1,-2,-6],
                [0, 3, 7],
                [1,-2, 5]])

In [ ]:
 # primer sistema tiene soluciones infinitas 
np.linalg.det(a_1)

0.0

In [ ]:
np.linalg.solve(a_2, b_2)

array([[ 7.42424242],
       [-1.24242424],
       [-0.18181818]])